### PR TITLE
add Lone Wolf & Mt Zozo checks to NFP

### PR DESCRIPTION
**Pull request by BriGuy7727**

### CODE REVIEW

**Comment by BriGuy7727** [comment]
From Trello card: https://trello.com/c/k2dgb75V/46-revisit-checks-included-in-no-free-characters-espers-lone-wolf-tzen-thief

Testing TBD

**Comment by dbldown11** [comment]
This needs an adjustment, the Trello card indicated we want Lone Wolf and Mt. Zozo to be on the NFP list, not Lone Wolf and Tzen Thief - Tzen Thief is to stay as-is.

**Comment by asilverthorn** [comment]
I made the requested mod on the dev branch: https://github.com/ff6wc/WorldsCollide/pull/109/commits/eee33d783d63c2791225e76f9eb34c928bd59d13

**Comment by asilverthorn** [comment]
Merged with https://github.com/ff6wc/WorldsCollide/pull/116

**Pull request closed without merging**
